name: build

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: show file
        run: |
          ls -al
      - name: build
        run: |
          base64 rules > autoproxy.txt
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with: 
          branch: build
          folder: .
